### ISSUE TITLE
Command line is not working

### ISSUE THREAD

**Issue by mooms06** [m417z/RAR-Unlocker#1]
Hi I'm trying to use your tool in command line, but it's throwing an error:

![image](https://github.com/user-attachments/assets/f1a5aff9-45dd-4779-b4b5-72389aab2887)

GUI is working.

What's the problem here ?

**Comment by m417z** [comment]
It must be either `-u` or `--unlock`, not `-unlock`.

**Comment by mooms06** [comment]
Thank you.
You should update the help window:

![image](https://github.com/user-attachments/assets/9c285865-16fc-4a6e-82ee-0083dc690857)

**Comment by m417z** [comment]
Thanks, I pushed a fix. It will be available in the next version, if one is ever released for this old tool.

**Comment by mooms06** [comment]
Maybe you could update the help/FAQ on your site and here on Github then, that could help other users.
Regards.

**Comment by m417z** [comment]
Yeah, good idea, done.
